name: CI-CD-WebApp
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run staging against '
        required: true
        default: ''
        type: choice
        options:
        - main
        - staging

      manualsetdeploy:
        description: 'Set checkBox if need set manual full image name'
        required: true
        # default: ''
        type: boolean
  push:
    branches:
      - 'main'

env:
  dockerfile: 'docker/docker-compose.yml'
  globalenv: ${{ steps.usedenv.outputs.SETENV }} #"${{ github.event.inputs.environment || '${GITHUB_REF_NAME}' }}"

jobs:
  set-envs:
    outputs:
      SETENV: ${{ steps.usedenv.outputs.SETENV }}
    runs-on: ubuntu-latest
    steps:
      # SET env depends on branch for commit action
      - name: SHOW used ENV
        id: usedenv
        run: |
          SETENV=${{ github.event.inputs.environment || '${GITHUB_REF_NAME}' }}
          echo "SETENV                                   === $SETENV"
          echo "SETENV=$SETENV"                          >> $GITHUB_OUTPUT
          mkdir -p ./path/to/artifact/
          echo "$SETENV"                                 >> ./path/to/artifact/$SETENV
          echo "SETENV=$SETENV"                          >> $GITHUB_ENV
          echo "globalenv                    ${globalenv}"

  docker-build:
    needs: [ set-envs ]
    if: ${{ github.event.inputs.manualsetdeploy != 'true'  }}
    outputs:
      SETENV: ${{ needs.set-envs.outputs.SETENV }}
    environment: ${{ needs.set-envs.outputs.SETENV }}
    runs-on: ubuntu-latest
    steps:
      - name: Show parameters
        id: chowparameters
        run: |
          BUILDNUMBER=$(date +%d.%m.%y_%H.%M)
          echo "${{ github.event.inputs.environment || '${GITHUB_REF_NAME}' }}"
          echo "globalenv                    ${globalenv}"

  update-webapp:
    if: ${{ always() }}
    needs: [ docker-build ]
    environment: ${{ needs.docker-build.outputs.SETENV }}
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        id: azlogin
        run: |
          echo "docker-build.outputs.SETENV     ${{ needs.docker-build.outputs.SETENV }}"
          echo "set-envs.outputs.SETENV         ${{ needs.set-envs.outputs.SETENV }}"
          echo "globalenv                    ${globalenv}"

  show-logs-webapp:
    if: ${{ always() }}
    needs: [ docker-build ]
    environment: ${{ needs.docker-build.outputs.SETENV }}
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        id: azlogin
        run: |
          echo "docker-build.outputs.SETENV     ${{ needs.docker-build.outputs.SETENV }}"
          echo "set-envs.outputs.SETENV         ${{ needs.set-envs.outputs.SETENV }}"
          echo "globalenv                    ${globalenv}"

